AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  TimeFunctionGR:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./
      Policies: AmazonDynamoDBFullAccess
      Events:
        MyTimeApiGR:
          Type: Api
          Properties:
            Path: /TimeResourceGR
            Method: GET
  HelloFunctionGR:
    Type: AWS::Serverless::Function
    Properties:
      Handler: hello.handler
      Runtime: nodejs6.10
      CodeUri: ./
      Policies: AmazonDynamoDBFullAccess
      Events:
        HelloTimeApiGR:
          Type: Api
          Properties:
            Path: /HelloResourceGR
            Method: GET
  GetMoviesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: movies/getMovies.handler
      Runtime: nodejs8.10
      CodeUri: ./src
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetMoviesApi:
          Type: Api
          Properties:
            Path: /movies
            Method: GET

  GetMovieFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: movies/getMovie.handler
      Runtime: nodejs8.10
      CodeUri: ./src
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetMovieApi:
          Type: Api
          Properties:
            Path: /movies/{id}
            Method: GET

  GetCategoriesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: category/getCategories.handler
      Runtime: nodejs8.10
      CodeUri: ./src
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetCategoriesApi:
          Type: Api
          Properties:
            Path: /categories
            Method: GET

  GetCategoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: category/getCategory.handler
      Runtime: nodejs8.10
      CodeUri: ./src
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetCategoryApi:
          Type: Api
          Properties:
            Path: /categories/{id}
            Method: GET


  PostCategoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: category/postCategory.handler
      Runtime: nodejs8.10
      CodeUri: ./src
      Policies: AmazonDynamoDBFullAccess
      Events:
        PostCategoryApi:
          Type: Api
          Properties:
            Path: /categories
            Method: POST

  PutCategoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: category/putCategory.handler
      Runtime: nodejs8.10
      CodeUri: ./src
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetCategoryApi:
          Type: Api
          Properties:
            Path: /categories
            Method: PUT

  DeleteCategoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: category/deleteCategory.handler
      Runtime: nodejs8.10
      CodeUri: ./src
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetCategoryApi:
          Type: Api
          Properties:
            Path: /categories/{id}
            Method: DELETE